# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'FlavoursKitDemo'

target 'FlavoursKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlavoursKitDemo
  pod 'FlavoursKit', :path => '../'	

end
